package com.example.lchav62.classes;

import androidx.room.Entity;
import androidx.room.Ignore;
import androidx.room.PrimaryKey;

@Entity(tableName = "VacationData")
public class VacationModel {

    // Primary key auto-generated by the database
    @PrimaryKey(autoGenerate = true)
    private int vacationId;

    // Fields representing vacation information
    private String vacationTitle;
    private String vacationLodging;
    private String vacationStartDate;
    private String vacationEndDate;

    // Constructor without arguments (used by Room for database operations)
    @Ignore
    public VacationModel() {
        // No args constructor required by Room for database operations
    }

    // Constructor with arguments to initialize vacation information
    public VacationModel(int vacationId, String vacationTitle, String vacationLodging,
                         String vacationStartDate, String vacationEndDate) {
        this.vacationId = vacationId;
        this.vacationTitle = vacationTitle;
        this.vacationLodging = vacationLodging;
        this.vacationStartDate = vacationStartDate;
        this.vacationEndDate = vacationEndDate;
    }

    // Getter and setter methods for vacation fields

    public int getVacationId() {
        return vacationId;
    }

    public void setVacationId(int vacationId) {
        this.vacationId = vacationId;
    }

    public String getVacationTitle() {
        return vacationTitle;
    }

    public void setVacationTitle(String vacationTitle) {
        this.vacationTitle = vacationTitle;
    }

    public String getVacationLodging() {
        return vacationLodging;
    }

    public void setVacationLodging(String vacationLodging) {
        this.vacationLodging = vacationLodging;
    }

    public String getVacationStartDate() {
        return vacationStartDate;
    }

    public void setVacationStartDate(String vacationStartDate) {
        this.vacationStartDate = vacationStartDate;
    }

    public String getVacationEndDate() {
        return vacationEndDate;
    }

    public void setVacationEndDate(String vacationEndDate) {
        this.vacationEndDate = vacationEndDate;
    }
}
